ucp_hello_world: ucp_hello_world.c
	gcc -o ucp_hello_world ucp_hello_world.c -lucp -lucs -luct

uct_hello_world: uct_hello_world.c
	gcc -o uct_hello_world uct_hello_world.c -lucp -lucs -luct

ucp_client_server: ucp_client_server.c
	gcc -o ucp_client_server ucp_client_server.c -lucp -lucs -luct